language: python
python: 3.8
# [3.8, 3.7, 3.6, 3.5, 3.4, 3.3, pypy, 2.7, 2.6]

#install:
#- pip install tox-travis
script:
- echo "No scripts"
#- tox
#- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$TRAVIS_TAG" = "$(python setup.py --version)" ]]'
#- |
#  if git show --format=%B --quiet "${TRAVIS_PULL_REQUEST_SHA:-${TRAVIS_TAG:-${TRAVIS_COMMIT}}}" \
#     | grep '\[changelog skip\]' > /dev/null; then
#    echo "Skip changelog checker..."
#  elif [[ "$TRAVIS_TAG" != "" ]]; then
#    ! grep -i "to be released" CHANGES.rst
#  else
#    [[ "$TRAVIS_COMMIT_RANGE" = "" ]] || \
#    [[ "$(git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep doc/changelog\.rst)" != "" ]]
#  fi

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    python: 3.8
    tags: true
